redirectsOrigin = "config"
plugins = []
headers = []

[functions]

[functions."*"]

[build]
publish = "/Users/kushagraagarwal/Documents/zryth/gym/frontend/dist"
publishOrigin = "config"
commandOrigin = "config"
base = "/Users/kushagraagarwal/Documents/zryth/gym/frontend"
command = "npm run build"

[build.environment]
NODE_VERSION = "20"
VITE_API_URL = "https://fitcheck-backend-0c7q.onrender.com/api"
VITE_APP_URL = "https://fitcheck-by-anmol.netlify.app"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]